//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorpApp_lab2
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusicTrack
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MusicTrack()
        {
            this.Playlists = new HashSet<Playlist>();
        }
    
        public int TrackId { get; set; }
        public string TrackName { get; set; }
        public string TrackAuthor { get; set; }
        public int GenreId { get; set; }
        public int UploadUserId { get; set; }
    
        public virtual Genre Genres { get; set; }
        public virtual User Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Playlist> Playlists { get; set; }
    }
}
