//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CorpApp_lab2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Playlist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Playlist()
        {
            this.MusicTracks = new HashSet<MusicTrack>();
        }
    
        public int PlaylistId { get; set; }
        public string PlaylistName { get; set; }
        public int PlaylistOwnerId { get; set; }
    
        public virtual User Users { get; set; }
        public virtual ICollection<MusicTrack> MusicTracks { get; set; }
    }
}
